#unsupported tests are commented out
STATISTICAL_TESTS_CHOICES = (
    ('', 'Please select an option'),
#    ('1ANCOVA', 'One-way ANCOVA'),
#    ('1ANOVA', 'One-way ANOVA'),
#    ('1CHIVAR', 'One-sample chi-squared test for variances'),
    ('1T-TEST', 'One-sample t-test'),
#    ('1Z-TEST', 'One-sample z-test'),
#    ('1-INCID', 'One-sample test for incidence rates'),
#    ('2ANCOVA', 'Two-way ANCOVA'),
#    ('2ANOVA', 'Two-way ANOVA'),
#    ('2F-TEST', 'Two-sample F-test to compare variances'),
#    ('2TEQUAL', 'Two-sample t-test with equal variances'),
#    ('2T-UNEQ', 'Two-sample t-test with unequal variances'),
#    ('2X2CONT', '2 x 2 contingency table methods'),
#    ('2XKCHI2', 'Chi-squared test for heterogeneity for 2 x k tables'),
#    ('2-BINOM', 'Two-sample test for binomial proportions'),
#    ('2-INCID', 'Two-sample test for comparison of incidence rates'),
#    ('CHITREN', 'Chi-squared test for trend'),
#    ('CONTING', 'Contingency-table methods'),
#    ('COXPHZD', 'Cox proportional-hazards model'),
#    ('EXACT', 'Exact methods'),
#    ('FISHERS', 'Fisher\'s exact test'),
#    ('HANCOVA', 'Higher-way ANCOVA'),
#    ('HANOVA', 'Higher-way ANOVA'),
#    ('KRUSKAL', 'Kruskal-Wallis test'),
#    ('KAPPA', 'Kappa statistic'),
#    ('LIN-REG', 'Simple linear regression'),
#    ('LOGRANK', 'Log-rank test'), 
#    ('MANEXT', 'Mantel Extension test'),
#    ('MANHAEN', 'Mantel-Haenszel test'),
#    ('MCNEMAR', 'McNemar\'s test'),
#    ('MUL-LR', 'Multiple logistic-regression methods'),
#    ('MUL-REG', 'Multiple-regression methods'),
#    ('NORMTHR', 'Normal-theory methods'),
#    ('PAIREDT', 'Paired t-test'),
#    ('PEARSON', 'Pearson correlation methods'),
#    ('POISSON', 'One-sample Poisson test'),
#    ('RANKCOR', 'Rank-correlation methods'),
#    ('RCTABLE', 'R x C contingency table methods'),
#    ('RXCCHI2', 'Chi-squared test for R x C tables'),
#    ('STRATPT', 'Stratified person-time data'),
#    ('TRENDIN', 'Test of trend for incidence rates'),
#    ('WEIBULL', 'Parameter survival methods based on weibull distribution'),
)